// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.cache.disk.amount_written", 1);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.search.region", "KR");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "68.10.0");
user_pref("extensions.lastPlatformVersion", "68.10.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"wetransfer@extensions.thunderbird.net\":\"c9267909-db55-4ffb-956e-6aeec2bc5d0d\",\"default-theme@mozilla.org\":\"ceb44f1a-2c72-4c87-b7a6-8024cf605eb9\",\"google@search.mozilla.org\":\"fb31a0a4-d7ac-4bd1-9bc5-b33e58838819\",\"amazondotcom@search.mozilla.org\":\"247bb89d-4aaf-47f9-a555-95c418d504f8\",\"bing@search.mozilla.org\":\"b3592e4b-5644-46e9-aac9-5a90c3125af8\",\"ddg@search.mozilla.org\":\"7a0cd6db-f77e-4b00-a6d5-52a8133c64d4\",\"twitter@search.mozilla.org\":\"f088b52b-6712-433c-8d14-4c73ba6df7ff\",\"wikipedia@search.mozilla.org\":\"d5905c5c-8bab-4e19-a0d0-29fdc4a59261\"}");
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.append_preconfig_smtpservers.version", 2);
user_pref("mail.default_charsets.migrated", 1);
user_pref("mail.folder.views.version", 1);
user_pref("mail.openMessageBehavior.version", 1);
user_pref("mail.spam.version", 1);
user_pref("mail.ui-rdf.version", 17);
user_pref("mailnews.database.global.datastore.id", "41cee940-9650-4cc9-ab0b-240bd37393c");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "68.10.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("security.sandbox.plugin.tempDirSuffix", "deae8664-10e2-4006-ad6b-ec673aade0ad");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.telemetry.prompted", 2);
